version: 1
update_configs:
  - 
    package_manager: javascript
    directory: /
    update_schedule: 住む
    allowed_updates:
      - 
        match:
          update_type: 安全
    automerged_updates:
      - 
        match:
          dependency_type: 全て
          update_type: 範囲内で
    version_requirement_updates: widen_ranges
