backend:
  name: git-gateway
media_folder: "サイト/静的/img" #Folder where user uploaded files should go
public_folder: "img"
collections:  #A list of collections the CMS should be able to edit
  - 
    name: "役職" #Used in routes, ie.: /admin/collections/:slug/edit
    label: "役職" #Used in the UI, ie.: "New Post"
    folder: "サイト/コンテンツ/投稿" #The path to the folder where the documents are stored
    create: true #Allow users to create new documents in this collection
    fields:  #The fields each document in this collection have
      - 
        label: "題名"
        name: "題名"
        widget: "ストリング"
      - 
        label: "公開日"
        name: "日にち"
        widget: "日付時刻"
      - 
        label: "イントロ宣伝文"
        name: "説明"
        widget: "文章"
      - 
        label: "画像"
        name: "画像"
        widget: "画像"
        required: false
      - 
        label: "体"
        name: "体"
        widget: "マークダウン"
  - 
    name: "ページ"
    label: "ページ"
    files:
      - 
        file: "site / content / _index.md"
        label: "ホームページ"
        name: "家"
        fields:
          - 
            label: 題名
            name: 題名
            widget: ストリング
          - 
            label: 字幕
            name: 字幕
            widget: ストリング
          - 
            label: 画像
            name: 画像
            widget: 画像
          - 
            "{label":
              "Text", name:
                "text", widget: '"文章"}]}'
          - 
            "{label":
              "Text", name:
                "text", widget: '"文章"}]}'
          - 
            "{label":
              "Text", name:
                "text", widget: '"文章"}]}'
          - 
            "{label":
              "Text", name:
                "text", widget: '"文章"}]}'
      - 
        file: "site / content / contact / _index.md"
        label: "お問い合わせページ"
        name: "コンタクト"
        fields:
          - 
            label: 題名
            name: 題名
            widget: ストリング
          - 
            label: ロゴ
            name: ロゴ
            widget: 画像
          - 
            label: 体
            name: 体
            widget: マークダウン
          - 
            label: 連絡先エントリ
            name: contact_entries
            widget: リスト
            fields:
              - 
                label: 見出し
                name: 見出し
                widget: ストリング
              - 
                label: 文章
                name: 文章
                widget: 文章
      - 
        file: "site / content / products / _index.md"
        label: "製品ページ"
        name: "製品"
        fields:
          - 
            label: 題名
            name: 題名
            widget: ストリング
          - 
            label: 画像
            name: 画像
            widget: 画像
          - 
            label: 見出し
            name: 見出し
            widget: ストリング
          - 
            label: 説明
            name: 説明
            widget: ストリング
          - 
            label: イントロ
            name: イントロ
            widget: 物体
            fields:
              - 
                label: 見出し
                name: 見出し
                widget: ストリング
              - 
                label: 説明
                name: 説明
                widget: 文章
              - 
                label: 宣伝文句
                name: 宣伝文
                widget: リスト
                fields:
                  - 
                    label: 画像
                    name: 画像
                    widget: 画像
                  - 
                    label: 文章
                    name: 文章
                    widget: 文章
          - 
            label: 主要
            name: 主要
            widget: 物体
            fields:
              - 
                label: 見出し
                name: 見出し
                widget: ストリング
              - 
                label: 説明
                name: 説明
                widget: 文章
              - 
                label: Image1
                name: image1
                widget: 物体
                fields:
                  - 
                    label: 画像
                    name: 画像
                    widget: 画像
                  - 
                    label: Alt
                    name: alt
                    widget: ストリング
              - 
                label: Image2
                name: image2
                widget: 物体
                fields:
                  - 
                    label: 画像
                    name: 画像
                    widget: 画像
                  - 
                    label: Alt
                    name: alt
                    widget: ストリング
              - 
                label: Image3
                name: image3
                widget: 物体
                fields:
                  - 
                    label: 画像
                    name: 画像
                    widget: 画像
                  - 
                    label: Alt
                    name: alt
                    widget: ストリング
          - 
            label: お客様の声
            name: お客様の声
            widget: リスト
            fields:
              - 
                label: 見積もり
                name: 見積もり
                widget: ストリング
              - 
                label: 著者
                name: 著者
                widget: ストリング
          - 
            label: Full_image
            name: full_image
            widget: 画像
          - 
            label: 価格設定
            name: 価格設定
            widget: 物体
            fields:
              - 
                label: 見出し
                name: 見出し
                widget: ストリング
              - 
                label: 説明
                name: 説明
                widget: ストリング
              - 
                label: 予定
                name: 予定
                widget: リスト
                fields:
                  - 
                    label: プラン
                    name: 予定
                    widget: ストリング
                  - 
                    label: 価格
                    name: 価格
                    widget: ストリング
                  - 
                    label: 説明
                    name: 説明
                    widget: ストリング
                  - 
                    label: アイテム
                    name: アイテム
                    widget: リスト
      - 
        file: "site / content / values / _index.md"
        label: "値のページ"
        name: "値"
        fields:
          - 
            label: 題名
            name: 題名
            widget: ストリング
          - 
            label: 画像
            name: 画像
            widget: 画像
          - 
            label: 値
            name: 値
            widget: リスト
            fields:
              - 
                label: 見出し
                name: 見出し
                widget: ストリング
              - 
                label: 文章
                name: 文章
                widget: 文章
              - 
                label: 画像
                name: imageUrl
                widget: 画像
