backend:
  name: गिट-गेटवे
media_folder: "साइट/स्थिर/आईएमजी" #Folder where user uploaded files should go
public_folder: "आईएमजी"
collections:  #A list of collections the CMS should be able to edit
  - 
    name: "पद" #Used in routes, ie.: /admin/collections/:slug/edit
    label: "पद" #Used in the UI, ie.: "New Post"
    folder: "साइट/सामग्री/पोस्ट" #The path to the folder where the documents are stored
    create: true #Allow users to create new documents in this collection
    fields:  #The fields each document in this collection have
      - 
        label: "शीर्षक"
        name: "शीर्षक"
        widget: "डोरी"
      - 
        label: "प्रकाशित तिथि"
        name: "दिनांक"
        widget: "दिनांक और समय"
      - 
        label: "इंट्रो ब्लर्ब"
        name: "विवरण"
        widget: "मूलपाठ"
      - 
        label: "छवि"
        name: "छवि"
        widget: "छवि"
        required: false
      - 
        label: "शरीर"
        name: "तन"
        widget: "markdown"
  - 
    name: "पृष्ठों"
    label: "पृष्ठों"
    files:
      - 
        file: "साइट/सामग्री/_index.md"
        label: "होम पेज"
        name: "घर"
        fields:
          - 
            label: शीर्षक
            name: शीर्षक
            widget: डोरी
          - 
            label: उपशीर्षक
            name: उपशीर्षक
            widget: डोरी
          - 
            label: छवि
            name: छवि
            widget: छवि
          - 
            "{label":
              "Text", name:
                "text", widget: '"मूलपाठ"}]}'
          - 
            "{label":
              "Text", name:
                "text", widget: '"मूलपाठ"}]}'
          - 
            "{label":
              "Text", name:
                "text", widget: '"मूलपाठ"}]}'
          - 
            "{label":
              "Text", name:
                "text", widget: '"मूलपाठ"}]}'
      - 
        file: "साइट/सामग्री/संपर्क/_index.md"
        label: "संपर्क पृष्ठ"
        name: "संपर्क Ajay करें"
        fields:
          - 
            label: शीर्षक
            name: शीर्षक
            widget: डोरी
          - 
            label: प्रतीक चिन्ह
            name: प्रतीक चिन्ह
            widget: छवि
          - 
            label: शरीर
            name: तन
            widget: markdown
          - 
            label: संपर्क प्रविष्टियां
            name: contact_entries
            widget: सूची
            fields:
              - 
                label: शीर्षक
                name: शीर्षक
                widget: डोरी
              - 
                label: मूलपाठ
                name: मूलपाठ
                widget: मूलपाठ
      - 
        file: "साइट/सामग्री/उत्पाद/_index.md"
        label: "उत्पाद पृष्ठ"
        name: "उत्पादों"
        fields:
          - 
            label: शीर्षक
            name: शीर्षक
            widget: डोरी
          - 
            label: छवि
            name: छवि
            widget: छवि
          - 
            label: शीर्षक
            name: शीर्षक
            widget: डोरी
          - 
            label: विवरण
            name: विवरण
            widget: डोरी
          - 
            label: पहचान
            name: परिचय
            widget: वस्तु
            fields:
              - 
                label: शीर्षक
                name: शीर्षक
                widget: डोरी
              - 
                label: विवरण
                name: विवरण
                widget: मूलपाठ
              - 
                label: ब्लर्ब
                name: ब्लर्ब
                widget: सूची
                fields:
                  - 
                    label: छवि
                    name: छवि
                    widget: छवि
                  - 
                    label: मूलपाठ
                    name: मूलपाठ
                    widget: मूलपाठ
          - 
            label: मुख्य
            name: मुख्य
            widget: वस्तु
            fields:
              - 
                label: शीर्षक
                name: शीर्षक
                widget: डोरी
              - 
                label: विवरण
                name: विवरण
                widget: मूलपाठ
              - 
                label: छवि1
                name: छवि1
                widget: वस्तु
                fields:
                  - 
                    label: छवि
                    name: छवि
                    widget: छवि
                  - 
                    label: Alt
                    name: Alt
                    widget: डोरी
              - 
                label: छवि2
                name: छवि2
                widget: वस्तु
                fields:
                  - 
                    label: छवि
                    name: छवि
                    widget: छवि
                  - 
                    label: Alt
                    name: Alt
                    widget: डोरी
              - 
                label: छवि 3
                name: छवि 3
                widget: वस्तु
                fields:
                  - 
                    label: छवि
                    name: छवि
                    widget: छवि
                  - 
                    label: Alt
                    name: Alt
                    widget: डोरी
          - 
            label: प्रशंसापत्र
            name: प्रशंसापत्र
            widget: सूची
            fields:
              - 
                label: उद्धरण
                name: उद्धरण
                widget: डोरी
              - 
                label: लेखक
                name: लेखक
                widget: डोरी
          - 
            label: फुल_इमेज
            name: फुल_इमेज
            widget: छवि
          - 
            label: मूल्य निर्धारण
            name: मूल्य निर्धारण
            widget: वस्तु
            fields:
              - 
                label: शीर्षक
                name: शीर्षक
                widget: डोरी
              - 
                label: विवरण
                name: विवरण
                widget: डोरी
              - 
                label: योजनाओं
                name: योजनाओं
                widget: सूची
                fields:
                  - 
                    label: योजना
                    name: योजना
                    widget: डोरी
                  - 
                    label: कीमत
                    name: कीमत
                    widget: डोरी
                  - 
                    label: विवरण
                    name: विवरण
                    widget: डोरी
                  - 
                    label: सामान
                    name: सामान
                    widget: सूची
      - 
        file: "साइट/सामग्री/मान/_index.md"
        label: "मान पृष्ठ"
        name: "मूल्यों"
        fields:
          - 
            label: शीर्षक
            name: शीर्षक
            widget: डोरी
          - 
            label: छवि
            name: छवि
            widget: छवि
          - 
            label: मूल्यों
            name: मूल्यों
            widget: सूची
            fields:
              - 
                label: शीर्षक
                name: शीर्षक
                widget: डोरी
              - 
                label: मूलपाठ
                name: मूलपाठ
                widget: मूलपाठ
              - 
                label: छवि
                name: छवि यूआरएल
                widget: छवि
