version: 1
update_configs:
  - 
    package_manager: जावास्क्रिप्ट
    directory: /
    update_schedule: लाइव
    allowed_updates:
      - 
        match:
          update_type: सुरक्षा
    automerged_updates:
      - 
        match:
          dependency_type: सब
          update_type: रेंज में
    version_requirement_updates: चौड़ा_रेंज
